In [326]:
import numpy as np
import pandas as pd
from pathlib import Path

In [327]:
# Path
_BASE_PATH= Path.cwd().parent
_DATA_PATH= _BASE_PATH / "data" / "raw" / "telco.csv"
_MODEL_FOLDER_PATH= _BASE_PATH / "models"

print("Dataset Path:\n", _DATA_PATH)

Dataset Path:
 c:\Users\emin.ocak\Desktop\aiAgentSQL\projelerileyapayzeka\projects\telco-customer-churn\data\raw\telco.csv

In [328]:
# Read to the dataset
df = pd.read_csv(_DATA_PATH)
print("Datased readed.")

Datased readed.

In [329]:
delete_columns = ["Churn Score", "Customer Status", "City", "Longitude", "Offer", "Quarter", "Zip Code", "Latitude", "State", "Country", "Customer ID", "Number of Dependents", "Dependents", "Under 30", "Senior Citizen", "Married", "Online Security", "Online Backup", "Device Protection Plan", "Streaming TV", "Streaming Movies", "Streaming Music", "Total Refunds", "Total Extra Data Charges", "Total Long Distance Charges", "Total Revenue", "Satisfaction Score", "Churn Reason", "Churn Category", "CLTV"]

df = df.drop(delete_columns, axis=1, inplace=False)

In [330]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             7043 non-null   object
 1   Age                                7043 non-null   int64
 2   Population                         7043 non-null   int64
 3   Referred a Friend                  7043 non-null   object
 4   Number of Referrals                7043 non-null   int64
 5   Tenure in Months                   7043 non-null   int64
 6   Phone Service                      7043 non-null   object
 7   Avg Monthly Long Distance Charges  7043 non-null   float64
 8   Multiple Lines                     7043 non-null   object
 9   Internet Service                   7043 non-null   object
 10  Internet Type                      5517 non-null   object
 11  Avg Monthly GB Download            7043 non-null   int64
 12  Premium Tech Support               7043 non-null   object
 13  Unlimited Data                     7043 non-null   object
 14  Contract                           7043 non-null   object
 15  Paperless Billing                  7043 non-null   object
 16  Payment Method                     7043 non-null   object
 17  Monthly Charge                     7043 non-null   float64
 18  Total Charges                      7043 non-null   float64
 19  Churn Label                        7043 non-null   object
dtypes: float64(3), int64(5), object(12)
memory usage: 1.1+ MB

In [331]:
# Dataset description
df.describe()

,Age,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,22139.603294,1.951867,32.386767,22.958954,20.515405,64.761692,2280.381264
std,16.750352,21152.392837,3.001199,24.542061,15.448113,20.418940,30.090047,2266.220462
min,19.000000,11.000000,0.000000,1.000000,0.000000,0.000000,18.250000,18.800000
25%,32.000000,2344.000000,0.000000,9.000000,9.210000,3.000000,35.500000,400.150000
50%,46.000000,17554.000000,0.000000,29.000000,22.890000,17.000000,70.350000,1394.550000
75%,60.000000,36125.000000,3.000000,55.000000,36.395000,27.000000,89.850000,3786.600000
max,80.000000,105285.000000,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000

In [332]:
# Shape
df.shape

(7043, 20)

In [333]:
# Columns, our target variable is "Churn Label"
df.columns

Index(['Gender', 'Age', 'Population', 'Referred a Friend',
       'Number of Referrals', 'Tenure in Months', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Premium Tech Support', 'Unlimited Data', 'Contract',
       'Paperless Billing', 'Payment Method', 'Monthly Charge',
       'Total Charges', 'Churn Label'],
      dtype='object')

In [334]:
# Targer column data type
df['Churn Label'].dtype

dtype('O')

In [335]:
# Which column? How much None variable?
df.isnull().sum()

Gender                                  0
Age                                     0
Population                              0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Premium Tech Support                    0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Churn Label                             0
dtype: int64

In [336]:
print(df[df.isnull().any(axis=1)])

      Gender  Age  Population Referred a Friend  Number of Referrals  \
25      Male   79       34902               Yes                    1
41    Female   74         626                No                    0
199   Female   70       15975                No                    0
373     Male   69         798                No                    0
375   Female   80        1328               Yes                    1
...      ...  ...         ...               ...                  ...
7026  Female   25         732                No                    0
7027  Female   30       29340                No                    0
7028    Male   39       24924               Yes                    2
7034  Female   57       48690                No                    0
7038  Female   30        2182                No                    0

      Tenure in Months Phone Service  Avg Monthly Long Distance Charges  \
25                  11           Yes                              29.54
41                   8           Yes                              27.95
199                  1           Yes                              22.92
373                  1           Yes                              19.87
375                  1           Yes                              22.86
...                ...           ...                                ...
7026                51           Yes                              19.23
7027                39           Yes                               1.57
7028                12           Yes                              25.33
7034                 2           Yes                               6.85
7038                72           Yes                              22.77

     Multiple Lines Internet Service Internet Type  Avg Monthly GB Download  \
25               No               No           NaN                        0
41               No               No           NaN                        0
199              No               No           NaN                        0
373              No               No           NaN                        0
375              No               No           NaN                        0
...             ...              ...           ...                      ...
7026             No               No           NaN                        0
7027             No               No           NaN                        0
7028             No               No           NaN                        0
7034             No               No           NaN                        0
7038             No               No           NaN                        0

     Premium Tech Support Unlimited Data        Contract Paperless Billing  \
25                     No             No  Month-to-Month                No
41                     No             No  Month-to-Month                No
199                    No             No  Month-to-Month               Yes
373                    No             No  Month-to-Month                No
375                    No             No  Month-to-Month               Yes
...                   ...            ...             ...               ...
7026                   No             No        Two Year                No
7027                   No             No        Two Year                No
7028                   No             No  Month-to-Month               Yes
7034                   No             No  Month-to-Month               Yes
7038                   No             No        Two Year               Yes

       Payment Method  Monthly Charge  Total Charges Churn Label
25       Mailed Check           19.95         214.75         Yes
41    Bank Withdrawal           19.65         164.30         Yes
199   Bank Withdrawal           19.45          19.45         Yes
373       Credit Card           20.05          20.05         Yes
375       Credit Card           20.85          20.85         Yes
...               ...             ...            ...         ...
7026  Bank Withdrawal           20.65        1020.75          No
7027     Mailed Check           20.15         826.00          No
7028  Bank Withdrawal           19.20         239.00          No
7034     Mailed Check           20.05          39.25          No
7038  Bank Withdrawal           21.15        1419.40          No

[1526 rows x 20 columns]

In [337]:
print(df['Churn Label'].value_counts())
print("")
print(df['Churn Label'].value_counts(normalize=True))

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

Churn Label
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [338]:
# turn to numeric
print(df['Total Charges'].dtype)
df['Total Charges'] - pd.to_numeric(df['Total Charges'], errors='coerce')
df['Total Charges']

float64

0         39.65
1        633.30
2       1752.55
3       2514.50
4       2868.15
         ...
7038    1419.40
7039    1990.50
7040    7362.90
7041     346.45
7042    6844.50
Name: Total Charges, Length: 7043, dtype: float64

In [339]:
# none sutunlarini 0 ile doldur
df['Total Charges'].fillna(0, inplace=True)
df['Total Charges']

0         39.65
1        633.30
2       1752.55
3       2514.50
4       2868.15
         ...
7038    1419.40
7039    1990.50
7040    7362.90
7041     346.45
7042    6844.50
Name: Total Charges, Length: 7043, dtype: float64

In [340]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             7043 non-null   object
 1   Age                                7043 non-null   int64
 2   Population                         7043 non-null   int64
 3   Referred a Friend                  7043 non-null   object
 4   Number of Referrals                7043 non-null   int64
 5   Tenure in Months                   7043 non-null   int64
 6   Phone Service                      7043 non-null   object
 7   Avg Monthly Long Distance Charges  7043 non-null   float64
 8   Multiple Lines                     7043 non-null   object
 9   Internet Service                   7043 non-null   object
 10  Internet Type                      5517 non-null   object
 11  Avg Monthly GB Download            7043 non-null   int64
 12  Premium Tech Support               7043 non-null   object
 13  Unlimited Data                     7043 non-null   object
 14  Contract                           7043 non-null   object
 15  Paperless Billing                  7043 non-null   object
 16  Payment Method                     7043 non-null   object
 17  Monthly Charge                     7043 non-null   float64
 18  Total Charges                      7043 non-null   float64
 19  Churn Label                        7043 non-null   object
dtypes: float64(3), int64(5), object(12)
memory usage: 1.1+ MB

In [341]:
df['Internet Type'].value_counts(normalize=True)

Internet Type
Fiber Optic    0.550118
DSL            0.299438
Cable          0.150444
Name: proportion, dtype: float64

In [342]:
print(df['Internet Type'].isnull().sum())
df['Internet Type'].fillna("No Internet",inplace=True)
df['Internet Type']

1526

C:\Users\emin.ocak\AppData\Local\Temp\ipykernel_22736\994117526.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Internet Type'].fillna("No Internet",inplace=True)

0               DSL
1       Fiber Optic
2       Fiber Optic
3       Fiber Optic
4       Fiber Optic
           ...
7038    No Internet
7039          Cable
7040    Fiber Optic
7041            DSL
7042    Fiber Optic
Name: Internet Type, Length: 7043, dtype: object

In [343]:
df['Internet Type'].value_counts(normalize=True)

Internet Type
Fiber Optic    0.430924
DSL            0.234559
No Internet    0.216669
Cable          0.117848
Name: proportion, dtype: float64

In [344]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             7043 non-null   object
 1   Age                                7043 non-null   int64
 2   Population                         7043 non-null   int64
 3   Referred a Friend                  7043 non-null   object
 4   Number of Referrals                7043 non-null   int64
 5   Tenure in Months                   7043 non-null   int64
 6   Phone Service                      7043 non-null   object
 7   Avg Monthly Long Distance Charges  7043 non-null   float64
 8   Multiple Lines                     7043 non-null   object
 9   Internet Service                   7043 non-null   object
 10  Internet Type                      7043 non-null   object
 11  Avg Monthly GB Download            7043 non-null   int64
 12  Premium Tech Support               7043 non-null   object
 13  Unlimited Data                     7043 non-null   object
 14  Contract                           7043 non-null   object
 15  Paperless Billing                  7043 non-null   object
 16  Payment Method                     7043 non-null   object
 17  Monthly Charge                     7043 non-null   float64
 18  Total Charges                      7043 non-null   float64
 19  Churn Label                        7043 non-null   object
dtypes: float64(3), int64(5), object(12)
memory usage: 1.1+ MB

In [345]:
df['Churn Label']= df['Churn Label'].replace("Yes", 1)
df['Churn Label']= df['Churn Label'].replace("No", 0)

df['Internet Service']= df['Internet Service'].replace("Yes", 1)
df['Internet Service']= df['Internet Service'].replace("No", 0)

df['Internet Service']= df['Internet Service'].replace("Yes", 1)
df['Internet Service']= df['Internet Service'].replace("No", 0)

df['Gender']= df['Gender'].replace("Male", 1)
df['Gender']= df['Gender'].replace("Female", 0)

df['Paperless Billing']= df['Paperless Billing'].replace("Yes", 1)
df['Paperless Billing']= df['Paperless Billing'].replace("No", 0)

df['Premium Tech Support']= df['Premium Tech Support'].replace("Yes", 1)
df['Premium Tech Support']= df['Premium Tech Support'].replace("No", 0)

df= pd.get_dummies(df, drop_first=True)
df

C:\Users\emin.ocak\AppData\Local\Temp\ipykernel_22736\3326690272.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Churn Label']= df['Churn Label'].replace("No", 0)
C:\Users\emin.ocak\AppData\Local\Temp\ipykernel_22736\3326690272.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Internet Service']= df['Internet Service'].replace("No", 0)
C:\Users\emin.ocak\AppData\Local\Temp\ipykernel_22736\3326690272.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender']= df['Gender'].replace("Female", 0)
C:\Users\emin.ocak\AppData\Local\Temp\ipykernel_22736\3326690272.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Paperless Billing']= df['Paperless Billing'].replace("No", 0)
C:\Users\emin.ocak\AppData\Local\Temp\ipykernel_22736\3326690272.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Premium Tech Support']= df['Premium Tech Support'].replace("No", 0)

,Gender,Age,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Internet Service,Avg Monthly GB Download,Premium Tech Support,Paperless Billing,...,Phone Service_Yes,Multiple Lines_Yes,Internet Type_DSL,Internet Type_Fiber Optic,Internet Type_No Internet,Unlimited Data_Yes,Contract_One Year,Contract_Two Year,Payment Method_Credit Card,Payment Method_Mailed Check
0,1,78,68701,0,1,0.00,1,8,0,1,...,False,False,True,False,False,False,False,False,False,False
1,0,74,55668,1,8,48.85,1,17,0,1,...,True,True,False,True,False,True,False,False,True,False
2,1,71,47534,0,18,11.33,1,52,0,1,...,True,True,False,True,False,True,False,False,False,False
3,0,78,27778,1,25,19.76,1,12,0,1,...,True,False,False,True,False,True,False,False,False,False
4,0,80,26265,1,37,6.33,1,14,0,1,...,True,True,False,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,30,2182,0,72,22.77,0,0,0,1,...,True,False,False,False,True,False,False,True,False,False
7039,1,38,18980,1,24,36.05,1,24,1,1,...,True,True,False,False,False,True,True,False,False,True
7040,0,30,42,4,72,29.66,1,59,0,1,...,True,True,False,True,False,True,True,False,True,False
7041,0,32,301,1,11,0.00,1,17,0,1,...,False,False,True,False,False,True,False,False,False,False
7042,1,44,28819,0,66,30.96,1,11,1,1,...,True,False,False,True,False,True,False,True,False,False

In [346]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             7043 non-null   int64
 1   Age                                7043 non-null   int64
 2   Population                         7043 non-null   int64
 3   Number of Referrals                7043 non-null   int64
 4   Tenure in Months                   7043 non-null   int64
 5   Avg Monthly Long Distance Charges  7043 non-null   float64
 6   Internet Service                   7043 non-null   int64
 7   Avg Monthly GB Download            7043 non-null   int64
 8   Premium Tech Support               7043 non-null   int64
 9   Paperless Billing                  7043 non-null   int64
 10  Monthly Charge                     7043 non-null   float64
 11  Total Charges                      7043 non-null   float64
 12  Churn Label                        7043 non-null   int64
 13  Referred a Friend_Yes              7043 non-null   bool
 14  Phone Service_Yes                  7043 non-null   bool
 15  Multiple Lines_Yes                 7043 non-null   bool
 16  Internet Type_DSL                  7043 non-null   bool
 17  Internet Type_Fiber Optic          7043 non-null   bool
 18  Internet Type_No Internet          7043 non-null   bool
 19  Unlimited Data_Yes                 7043 non-null   bool
 20  Contract_One Year                  7043 non-null   bool
 21  Contract_Two Year                  7043 non-null   bool
 22  Payment Method_Credit Card         7043 non-null   bool
 23  Payment Method_Mailed Check        7043 non-null   bool
dtypes: bool(11), float64(3), int64(10)
memory usage: 791.1 KB

In [347]:
X = df.drop(columns='Churn Label')
y = df['Churn Label']

In [348]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, classification_report, precision_score

scaler= StandardScaler()

In [349]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

print(f"X_train: {len(X_train)} | X_test: {len(X_test)} | {len(y_train)} | {len(y_test)}")

X_train: 5634 | X_test: 1409 | 5634 | 1409

In [350]:
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

In [351]:
print("Original training data:\n", X_train)

Original training data:
       Gender  Age  Population  Number of Referrals  Tenure in Months  \
2663       0   38       43857                    9                69
2894       1   63       32268                    6                 7
2265       0   27       40836                    0                 1
4908       0   27       25859                    4                40
3621       1   40       33523                    9                71
...      ...  ...         ...                  ...               ...
3915       0   19       38519                    0                 1
1428       1   37        8525                    0                 1
6537       1   39       23570                    7                60
4367       0   59         128                    6                 2
2522       1   52       47431                    0                 4

      Avg Monthly Long Distance Charges  Internet Service  \
2663                               5.27                 0
2894                               5.17                 1
2265                              23.00                 1
4908                              42.10                 1
3621                              33.67                 1
...                                 ...               ...
3915                              29.13                 1
1428                              28.25                 1
6537                              27.20                 1
4367                              48.39                 1
2522                              47.82                 1

      Avg Monthly GB Download  Premium Tech Support  Paperless Billing  ...  \
2663                        0                     0                  0  ...
2894                       51                     0                  0  ...
2265                       59                     0                  1  ...
4908                       52                     0                  0  ...
3621                       75                     1                  1  ...
...                       ...                   ...                ...  ...
3915                       51                     0                  1  ...
1428                        9                     0                  1  ...
6537                       21                     1                  0  ...
4367                       24                     0                  1  ...
2522                       13                     0                  1  ...

      Phone Service_Yes  Multiple Lines_Yes  Internet Type_DSL  \
2663               True               False              False
2894               True               False              False
2265               True               False              False
4908               True                True               True
3621               True                True              False
...                 ...                 ...                ...
3915               True                True              False
1428               True                True              False
6537               True               False               True
4367               True               False              False
2522               True                True              False

      Internet Type_Fiber Optic  Internet Type_No Internet  \
2663                      False                       True
2894                      False                      False
2265                       True                      False
4908                      False                      False
3621                       True                      False
...                         ...                        ...
3915                      False                      False
1428                      False                      False
6537                      False                      False
4367                      False                      False
2522                       True                      False

      Unlimited Data_Yes  Contract_One Year  Contract_Two Year  \
2663               False              False               True
2894                True              False              False
2265                True              False              False
4908                True               True              False
3621                True              False               True
...                  ...                ...                ...
3915                True              False              False
1428                True              False              False
6537                True              False               True
4367                True              False              False
2522                True              False              False

      Payment Method_Credit Card  Payment Method_Mailed Check
2663                       False                        False
2894                        True                        False
2265                       False                        False
4908                       False                        False
3621                       False                        False
...                          ...                          ...
3915                       False                        False
1428                       False                        False
6537                       False                        False
4367                       False                         True
2522                       False                        False

[5634 rows x 23 columns]

In [352]:
print("\nScaled training data (mean=0, std=1):\n", X_train_scaled)

Scaled training data (mean=0, std=1):
 [[-1.01286226 -0.51012814  1.03011315 ...  1.63485503 -0.80130322
  -0.24539415]
 [ 0.98730107  0.97585098  0.47958665 ... -0.61167503  1.24796703
  -0.24539415]
 [-1.01286226 -1.16395895  0.88660288 ... -0.61167503 -0.80130322
  -0.24539415]
 ...
 [ 0.98730107 -0.45068897  0.06639488 ...  1.63485503 -0.80130322
  -0.24539415]
 [-1.01286226  0.73809432 -1.04719922 ... -0.61167503 -0.80130322
   4.07507669]
 [ 0.98730107  0.32202017  1.19989326 ... -0.61167503 -0.80130322
  -0.24539415]]

In [353]:
print("\nScaled test data:\n", X_test_scaled)

Scaled test data:
 [[-1.01286226 -1.40171561 -1.03271043 ... -0.61167503  1.24796703
  -0.24539415]
 [ 0.98730107  1.33248597 -0.87518641 ... -0.61167503 -0.80130322
  -0.24539415]
 [ 0.98730107  0.73809432  0.50870674 ...  1.63485503 -0.80130322
  -0.24539415]
 ...
 [ 0.98730107 -1.40171561 -0.24642046 ... -0.61167503  1.24796703
  -0.24539415]
 [-1.01286226  1.62968179  0.16135583 ... -0.61167503 -0.80130322
  -0.24539415]
 [-1.01286226 -0.80732396  0.53944198 ... -0.61167503 -0.80130322
  -0.24539415]]

In [354]:
# create model object
model = LogisticRegression(
    class_weight="balanced",
    penalty='l2',
    solver='sag',
    max_iter=1000
)

# train model with X scaled dataset
model.fit(X_train_scaled, y_train)

# test predict
y_pred = model.predict(X_test_scaled)

precision= precision_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)

# Valudations
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"Accuracy: %{accuracy_score(y_test, y_pred) * 100:.0f}")

Precision: 0.56
Recall: 0.83
Accuracy: %77

In [ ]:
import pickle

# model paths
scaler_path = _MODEL_FOLDER_PATH / "scaler.pkl"
model_path  =   _MODEL_FOLDER_PATH / "model.pkl"

# write models
with open(scaler_path, "wb") as f:
    pickle.dump(scaler, f)

with open(model_path, "wb") as f:
    pickle.dump(model, f)